// <auto-generated>
// This file was generated using the RhoMicro.CodeAnalysis.UnionsGenerator.
// </auto-generated>
#nullable enable
#pragma warning disable

namespace RhoMicro.CodeAnalysis
{
    using System;

    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
#if UNIONS_GENERATOR
    [GenerateFactory]
#endif
    sealed partial class UnionFactoryAttribute : Attribute { }
}
