namespace RhoMicro.CodeAnalysis.Library.Text;

using System.Collections.Immutable;
using System.Runtime.CompilerServices;
using System.Text;
using System.Threading;
partial class IndentedStringBuilder : IEquatable<IndentedStringBuilder?>
{
    public IndentedStringBuilder(IndentedStringBuilderOptions options)
    {
        Options = options;

        if(Options.PrependMarkerComment)
        {
            _ = _builder.AppendLine("// <auto-generated>");

            if(!String.IsNullOrWhiteSpace(Options.GeneratorName))
            {
                _ = _builder.Append("// This file was last generated by ")
                    .Append(Options.GeneratorName)
                    .Append(" at ")
                    .AppendLine(DateTimeOffset.Now.ToString());
            }

            _ = _builder
                .AppendLine("// The tool used to generate this code may be subject to license terms;")
                .AppendLine("// this generated code is however not subject to those terms, instead it is")
                .AppendLine("// subject to the license (if any) applied to the containing project.")
                .AppendLine("// </auto-generated>");
        }

        if(Options.PrependWarningDisablePragma)
            _ = _builder.AppendLine("#pragma warning disable");

        if(Options.PrependNullableEnable)
            _ = _builder.AppendLine("#nullable enable");

        Comment = new(this);
        Operators = new(this);
    }

    public IndentedStringBuilder() : this(IndentedStringBuilderOptions.Default)
    { }

    #region Fields & Properties
    public CommentBuilder Comment { get; }
    public OperatorsDecorator Operators { get; }
    public IndentedStringBuilderOptions Options { get; }
    private readonly StringBuilder _builder = new();
    private readonly Stack<Block> _blocks = new();
    private readonly Stack<StringOrChar> _indentations = new();
    private Block? LastBlock => _blocks.Count > 0 ? _blocks.Peek() : null;
    private Boolean LastWasNewLine
    {
        get
        {
            if(_builder.Length < Options.NewLine.Length)
                return false;

            for(var i = 1; i <= Options.NewLine.Length; i++)
            {
                if(_builder[^i] != Options.NewLine[^i])
                    return false;
            }

            return true;
        }
    }
    public Int32 OpenBlocks => _blocks.Count;
    #endregion
    #region Open Block
    public void OpenBlockCore(Block block)
    {
        var delimiter = block.OpeningDelimiter;

        if(block.PlaceDelimitersOnNewLine && !LastWasNewLine)
            AppendSingleLineCore();

        AppendCore(delimiter);

        _blocks.Push(block);

        var indentation = block.Indentation ?? Options.DefaultIndentation;
        _indentations.Push(indentation);
    }
    public IndentedStringBuilder OpenBlock(Block block)
    {
        OpenBlockCore(block);
        return this;
    }
    public IndentedStringBuilder OpenBracketsBlock() => OpenBlock(Blocks.Brackets);
    public IndentedStringBuilder OpenIndentBlock() => OpenBlock(Blocks.Indent);
    public IndentedStringBuilder OpenBracesBlock() => OpenBlock(Blocks.Braces(Options.NewLine));
    public IndentedStringBuilder OpenParensBlock() => OpenBlock(Blocks.Parens);
    public IndentedStringBuilder OpenAngledBlock() => OpenBlock(Blocks.Angled);
    public IndentedStringBuilder OpenRegionBlock(String name) => OpenBlock(Blocks.Region(name, Options.NewLine));
    #endregion
    #region Open Block Scope
    public BlockScope OpenBlockScope(Block block) => new(OpenBlock(block));
    public BlockScope OpenBracketsBlockScope() => new(OpenBracketsBlock());
    public BlockScope OpenIndentBlockScope() => new(OpenIndentBlock());
    public BlockScope OpenBracesBlockScope() => new(OpenBracesBlock());
    public BlockScope OpenParensBlockScope() => new(OpenParensBlock());
    public BlockScope OpenAngledBlockScope() => new(OpenAngledBlock());
    public BlockScope OpenRegionBlockScope(String name) => new(OpenRegionBlock(name));

    public IndentedStringBuilder OpenBlockScope(Block block, BlockScopeCollection scopes)
    {
        var scope = OpenBlockScope(block);
        scopes.AddScope(scope);
        return this;
        ;
    }
    public IndentedStringBuilder OpenBracketsBlockScope(BlockScopeCollection scopes) =>
        OpenBlockScope(Blocks.Brackets, scopes);
    public IndentedStringBuilder OpenIndentBlockScope(BlockScopeCollection scopes) =>
        OpenBlockScope(Blocks.Indent, scopes);
    public IndentedStringBuilder OpenBracesBlockScope(BlockScopeCollection scopes) =>
        OpenBlockScope(Blocks.Braces(Options.NewLine), scopes);
    public IndentedStringBuilder OpenParensBlockScope(BlockScopeCollection scopes) =>
        OpenBlockScope(Blocks.Parens, scopes);
    public IndentedStringBuilder OpenAngledBlockScope(BlockScopeCollection scopes) =>
        OpenBlockScope(Blocks.Angled, scopes);
    public IndentedStringBuilder OpenRegionBlockScope(String name, BlockScopeCollection scopes) =>
        OpenBlockScope(Blocks.Region(name, Options.NewLine), scopes);
    #endregion
    #region Close Block
    public void CloseBlockCore()
    {
        if(!LastBlock.HasValue)
            return;

        DetentUnsafeCore();

        var block = LastBlock.Value;

        if(block.PlaceDelimitersOnNewLine)
            AppendSingleLineCore();

        AppendCore(block.ClosingDelimiter);
        _ = _blocks.Pop();
    }
    public void CloseAllBlocksCore()
    {
        while(_blocks.Count > 0)
        {
            CloseBlockCore();
        }
    }
    public IndentedStringBuilder CloseBlock()
    {
        CloseBlockCore();
        return this;
    }
    public IndentedStringBuilder CloseAllBlocks()
    {
        CloseAllBlocksCore();
        return this;
    }
    #endregion
    #region Indent
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void IndentCore() => _indentations.Push(Options.DefaultIndentation);
    public IndentScope CreateIndentScope() => new(Indent());
    public IndentedStringBuilder Indent()
    {
        IndentCore();
        return this;
    }
    void ApplyIndentation()
    {
        if(!LastWasNewLine)
            return;

        foreach(var indentation in _indentations.Reverse())
        {
            ThrowIfCancellationRequested();

            _ = indentation.IsString ?
                _builder.Append((String)indentation) :
                _builder.Append((Char)indentation);
        }
    }
    #endregion
    #region Detent
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private void DetentUnsafeCore() => _ = _indentations.Pop();
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void DetentCore()
    {
        if(_indentations.Count > 0)
        {
            if(!_indentations.Peek().IsWhitespace)
                throw new InvalidOperationException("Attempted to detent non-whitespace indentation. Use 'CloseBlock' or 'CloseAllBlocks' instead.");

            DetentUnsafeCore();
        }
    }
    public IndentedStringBuilder Detent()
    {
        DetentCore();
        return this;
    }
    #endregion
    #region Append String
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    void AppendCoreNoIndentation(String value)
    {
        ThrowIfCancellationRequested();

        _ = _builder.Append(value);
    }
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void AppendCore(String value)
    {
        ApplyIndentation();
        AppendCoreNoIndentation(value);
    }
    public void Add(String value) => AppendCore(value);
    public IndentedStringBuilder Append(String value)
    {
        AppendCore(value);
        return this;
    }
    public IndentedStringBuilder Append(params String[] values)
    {
        for(var i = 0; i < values.Length; i++)
        {
            AppendCore(values[i]);
        }

        return this;
    }
    public IndentedStringBuilder Append(ImmutableArray<String> values)
    {
        for(var i = 0; i < values.Length; i++)
        {
            AppendCore(values[i]);
        }

        return this;
    }
    public IndentedStringBuilder Append(IEnumerable<String> values)
    {
        foreach(var value in values)
        {
            AppendCore(value);
        }

        return this;
    }
    #endregion
    #region Append Char
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    void AppendCoreNoIndentation(Char value)
    {
        ThrowIfCancellationRequested();

        _ = _builder.Append(value);
    }
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void AppendCore(Char value)
    {
        ApplyIndentation();
        AppendCoreNoIndentation(value);
    }
    public void Add(Char value) => AppendCore(value);
    public IndentedStringBuilder Append(Char value)
    {
        AppendCore(value);
        return this;
    }
    public IndentedStringBuilder Append(params Char[] values)
    {
        for(var i = 0; i < values.Length; i++)
        {
            AppendCore(values[i]);
        }

        return this;
    }
    public IndentedStringBuilder Append(ImmutableArray<Char> values)
    {
        for(var i = 0; i < values.Length; i++)
        {
            AppendCore(values[i]);
        }

        return this;
    }
    public IndentedStringBuilder Append(IEnumerable<Char> values)
    {
        foreach(var value in values)
        {
            AppendCore(value);
        }

        return this;
    }
    #endregion
    #region Append T
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    void AppendCoreNoIndentation<T>(T value)
        where T : IIndentedStringBuilderAppendable
        => value?.AppendTo(this);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void AppendCore<T>(T value)
        where T : IIndentedStringBuilderAppendable
    {
        ApplyIndentation();
        AppendCoreNoIndentation(value);
    }
    public void Add<T>(T value)
        where T : IIndentedStringBuilderAppendable
        => AppendCore(value);
    public IndentedStringBuilder Append<T>(T value)
        where T : IIndentedStringBuilderAppendable
    {
        AppendCore(value);
        return this;
    }
    public IndentedStringBuilder Append<T>(params T[] values)
        where T : IIndentedStringBuilderAppendable
    {
        for(var i = 0; i < values.Length; i++)
        {
            AppendCore(values[i]);
        }

        return this;
    }
    public IndentedStringBuilder Append<T>(ImmutableArray<T> values)
        where T : IIndentedStringBuilderAppendable
    {
        for(var i = 0; i < values.Length; i++)
        {
            AppendCore(values[i]);
        }

        return this;
    }
    public IndentedStringBuilder Append<T>(IEnumerable<T> values)
        where T : IIndentedStringBuilderAppendable
    {
        foreach(var value in values)
        {
            AppendCore(value);
        }

        return this;
    }
    #endregion
    #region Append Action
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    void AppendCoreNoIndentation(Action<IndentedStringBuilder> value)
        => value?.Invoke(this);
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void AppendCore(Action<IndentedStringBuilder> value)
    {
        ApplyIndentation();
        AppendCoreNoIndentation(value);
    }
    public void Add(Action<IndentedStringBuilder> value)
        => AppendCore(value);
    public IndentedStringBuilder Append(Action<IndentedStringBuilder> value)
    {
        AppendCore(value);
        return this;
    }
    public IndentedStringBuilder Append(params Action<IndentedStringBuilder>[] values)
    {
        for(var i = 0; i < values.Length; i++)
        {
            AppendCore(values[i]);
        }

        return this;
    }
    public IndentedStringBuilder Append(ImmutableArray<Action<IndentedStringBuilder>> values)
    {
        for(var i = 0; i < values.Length; i++)
        {
            AppendCore(values[i]);
        }

        return this;
    }
    public IndentedStringBuilder Append(IEnumerable<Action<IndentedStringBuilder>> values)
    {
        foreach(var value in values)
        {
            AppendCore(value);
        }

        return this;
    }
    #endregion
    #region Append Join
    public IndentedStringBuilder AppendJoin(IEnumerable<String> values) => AppendJoin(", ", values);
    public IndentedStringBuilder AppendJoin(StringOrChar separator, IEnumerable<String> values)
    {
        var enumerator = values.GetEnumerator();
        if(!enumerator.MoveNext())
            return this;

        AppendCore(enumerator.Current);

        while(enumerator.MoveNext())
        {
            AppendCore(separator);
            AppendCore(enumerator.Current);
        }

        return this;
    }
    public IndentedStringBuilder AppendJoinLines(IEnumerable<String> values) => AppendJoinLines(',', values);
    public IndentedStringBuilder AppendJoinLines(StringOrChar separator, IEnumerable<String> values)
    {
        var enumerator = values.GetEnumerator();
        if(!enumerator.MoveNext())
            return this;

        AppendCore(enumerator.Current);

        while(enumerator.MoveNext())
        {
            AppendCore(separator);
            AppendLineCore();
            AppendCore(enumerator.Current);
        }

        return this;
    }

    public IndentedStringBuilder AppendJoin(IEnumerable<Char> values) => AppendJoin(", ", values);
    public IndentedStringBuilder AppendJoin(StringOrChar separator, IEnumerable<Char> values)
    {
        var enumerator = values.GetEnumerator();
        if(!enumerator.MoveNext())
            return this;

        AppendCore(enumerator.Current);

        while(enumerator.MoveNext())
        {
            AppendCore(separator);
            AppendCore(enumerator.Current);
        }

        return this;
    }
    public IndentedStringBuilder AppendJoinLines(IEnumerable<Char> values) => AppendJoinLines(',', values);
    public IndentedStringBuilder AppendJoinLines(StringOrChar separator, IEnumerable<Char> values)
    {
        var enumerator = values.GetEnumerator();
        if(!enumerator.MoveNext())
            return this;

        AppendCore(enumerator.Current);

        while(enumerator.MoveNext())
        {
            AppendCore(separator);
            AppendLineCore();
            AppendCore(enumerator.Current);
        }

        return this;
    }

    public IndentedStringBuilder AppendJoin<T>(IEnumerable<T> values)
        where T : IIndentedStringBuilderAppendable
        => AppendJoin(", ", values);
    public IndentedStringBuilder AppendJoin<T>(StringOrChar separator, IEnumerable<T> values)
        where T : IIndentedStringBuilderAppendable
    {
        var enumerator = values.GetEnumerator();
        if(!enumerator.MoveNext())
            return this;

        AppendCore(enumerator.Current);

        while(enumerator.MoveNext())
        {
            AppendCore(separator);
            AppendCore(enumerator.Current);
        }

        return this;
    }
    public IndentedStringBuilder AppendJoinLines<T>(IEnumerable<T> values)
        where T : IIndentedStringBuilderAppendable
        => AppendJoinLines(',', values);
    public IndentedStringBuilder AppendJoinLines<T>(StringOrChar separator, IEnumerable<T> values)
        where T : IIndentedStringBuilderAppendable
    {
        var enumerator = values.GetEnumerator();
        if(!enumerator.MoveNext())
            return this;

        AppendCore(enumerator.Current);

        while(enumerator.MoveNext())
        {
            AppendCore(separator);
            AppendLineCore();
            AppendCore(enumerator.Current);
        }

        return this;
    }

    public IndentedStringBuilder AppendJoin(IEnumerable<Action<IndentedStringBuilder>> values) => AppendJoin(", ", values);
    public IndentedStringBuilder AppendJoin(StringOrChar separator, IEnumerable<Action<IndentedStringBuilder>> values)
    {
        var enumerator = values.GetEnumerator();
        if(!enumerator.MoveNext())
            return this;

        AppendCore(enumerator.Current);

        while(enumerator.MoveNext())
        {
            AppendCore(separator);
            AppendCore(enumerator.Current);
        }

        return this;
    }
    public IndentedStringBuilder AppendJoinLines(IEnumerable<Action<IndentedStringBuilder>> values) => AppendJoinLines(',', values);
    public IndentedStringBuilder AppendJoinLines(StringOrChar separator, IEnumerable<Action<IndentedStringBuilder>> values)
    {
        var enumerator = values.GetEnumerator();
        if(!enumerator.MoveNext())
            return this;

        AppendCore(enumerator.Current);

        while(enumerator.MoveNext())
        {
            AppendCore(separator);
            AppendLineCore();
            AppendCore(enumerator.Current);
        }

        return this;
    }
    #endregion
    #region Append Line
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void AppendLineCore()
    {
        ThrowIfCancellationRequested();

        _ = Options.NewLine.IsString ?
            _builder.Append((String)Options.NewLine) :
            _builder.Append((Char)Options.NewLine);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private void AppendSingleLineCore()
    {
        if(LastWasNewLine)
            return;

        AppendLineCore();
    }
    public IndentedStringBuilder AppendLine()
    {
        AppendLineCore();
        return this;
    }
    public IndentedStringBuilder AppendLine(String value) => Append(value).AppendLine();
    public IndentedStringBuilder AppendLine(Char value) => Append(value).AppendLine();
    public IndentedStringBuilder AppendLine(Action<IndentedStringBuilder> value) => Append(value).AppendLine();
    public IndentedStringBuilder AppendLine<T>(T value)
        where T : IIndentedStringBuilderAppendable
        => Append(value).AppendLine();
    #endregion
    #region ToString & Equality
    public IndentedStringBuilder Clear()
    {
        _indentations.Clear();
        _blocks.Clear();
        _ = _builder.Clear();
        return this;
    }
    public override String ToString() => _builder.ToString();
    public override Boolean Equals(Object? obj) => Equals(obj as IndentedStringBuilder);
    public Boolean Equals(IndentedStringBuilder? other) =>
        other is not null &&
        CollectionEqualityComparer<StringOrChar>.Default.Equals(_indentations, other._indentations) &&
        CollectionEqualityComparer<Block>.Default.Equals(_blocks, other._blocks) &&
        EqualityComparer<StringBuilder>.Default.Equals(_builder, other._builder);
    public override Int32 GetHashCode() =>
        (
            _builder,
            CollectionEqualityComparer<StringOrChar>.Default.GetHashCode(_indentations),
            CollectionEqualityComparer<Block>.Default.GetHashCode(_blocks)
        ).GetHashCode();
    #endregion
    #region Cancellation
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private void ThrowIfCancellationRequested() => Options.AmbientCancellationToken.ThrowIfCancellationRequested();
    #endregion
}
